# Generated by Django 2.0.4 on 2018-04-22 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distinguished_name', models.TextField(max_length=100, verbose_name='Distinguished name')),
                ('display_name', models.TextField(blank=True, default=None, max_length=500, null=True, verbose_name='Display name')),
                ('description', models.TextField(blank=True, default=None, max_length=5000, null=True, verbose_name='Description')),
                ('_configuration', models.TextField(verbose_name='Configuration')),
            ],
        ),
        migrations.CreateModel(
            name='SchemaAttributeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distinguished_name', models.TextField(max_length=100, verbose_name='Distinguished name')),
                ('display_name', models.TextField(blank=True, default=None, max_length=500, null=True, verbose_name='Display name')),
                ('description', models.TextField(blank=True, default=None, max_length=5000, null=True, verbose_name='Description')),
                ('data_type', models.CharField(choices=[('date', 'Date'), ('datetime', 'Datetime'), ('float', 'Float'), ('int', 'Integer'), ('interval', 'Interval'), ('period', 'Period'), ('str', 'String'), ('time', 'Time')], default='str', max_length=20, verbose_name='Data type')),
                ('data_precision', models.IntegerField(default=3, verbose_name='Data precision')),
                ('representation_type', models.CharField(choices=[('date', 'Date'), ('number', 'Number'), ('text', 'Text')], default='text', max_length=20, verbose_name='Representation type')),
                ('representation_precision', models.IntegerField(default=3, verbose_name='Representation precision')),
                ('constrait_minimum', models.FloatField(blank=True, default=None, null=True)),
                ('constrait_maximum', models.FloatField(blank=True, default=None, null=True)),
                ('constrait_pattern', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('constrait_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SchemaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distinguished_name', models.TextField(max_length=100, verbose_name='Distinguished name')),
                ('display_name', models.TextField(blank=True, default=None, max_length=500, null=True, verbose_name='Display name')),
                ('description', models.TextField(blank=True, default=None, max_length=5000, null=True, verbose_name='Description')),
            ],
        ),
        migrations.AddField(
            model_name='schemaattributemodel',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrumentation.SchemaModel', verbose_name='Schema'),
        ),
        migrations.AddField(
            model_name='equipmentmodel',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrumentation.SchemaModel', verbose_name='Schema'),
        ),
    ]
