# Generated by Django 2.0.4 on 2018-04-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentmodel',
            options={'verbose_name': 'Equipment'},
        ),
        migrations.AlterField(
            model_name='equipmentmodel',
            name='display_name',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Display name'),
        ),
        migrations.AlterField(
            model_name='equipmentmodel',
            name='distinguished_name',
            field=models.CharField(max_length=100, verbose_name='Distinguished name'),
        ),
        migrations.AlterField(
            model_name='schemaattributemodel',
            name='display_name',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Display name'),
        ),
        migrations.AlterField(
            model_name='schemaattributemodel',
            name='distinguished_name',
            field=models.CharField(max_length=100, verbose_name='Distinguished name'),
        ),
        migrations.AlterField(
            model_name='schemamodel',
            name='display_name',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Display name'),
        ),
        migrations.AlterField(
            model_name='schemamodel',
            name='distinguished_name',
            field=models.CharField(max_length=100, verbose_name='Distinguished name'),
        ),
    ]
