# Generated by Django 2.0.4 on 2018-05-10 00:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsoleCommandModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('response_timestamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('request', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('response', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('error', models.CharField(blank=True, default=None, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConstantModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distinguished_name', models.CharField(max_length=100, verbose_name='Distinguished name')),
                ('display_name', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Display name')),
                ('description', models.TextField(blank=True, default=None, max_length=5000, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Constant',
            },
        ),
        migrations.CreateModel(
            name='EnumerationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distinguished_name', models.CharField(max_length=100, verbose_name='Distinguished name')),
                ('display_name', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Display name')),
                ('description', models.TextField(blank=True, default=None, max_length=5000, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Enumeration',
            },
        ),
        migrations.CreateModel(
            name='OperationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField(blank=True, default=None, max_length=5000, null=True, verbose_name='Source')),
            ],
            options={
                'verbose_name': 'Operation',
            },
        ),
        migrations.CreateModel(
            name='ParameterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representation_type', models.CharField(choices=[('date', 'Date'), ('number', 'Number'), ('text', 'Text')], default='text', max_length=20, verbose_name='Representation type')),
                ('representation_precision', models.IntegerField(default=3, verbose_name='Representation precision')),
                ('distinguished_name', models.CharField(max_length=100, verbose_name='Distinguished name')),
                ('display_name', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Display name')),
                ('description', models.TextField(blank=True, default=None, max_length=5000, null=True, verbose_name='Description')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrumentation.OperationModel', verbose_name='Operation')),
            ],
            options={
                'verbose_name': 'Parameter',
            },
        ),
        migrations.CreateModel(
            name='SchemaActionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distinguished_name', models.CharField(max_length=100, verbose_name='Distinguished name')),
                ('display_name', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Display name')),
                ('description', models.TextField(blank=True, default=None, max_length=5000, null=True, verbose_name='Description')),
                ('operation', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='instrumentation.OperationModel', verbose_name='Operation')),
            ],
            options={
                'verbose_name': 'Action',
            },
        ),
        migrations.AlterModelOptions(
            name='equipmentmodel',
            options={'verbose_name': 'Equipment'},
        ),
        migrations.AlterModelOptions(
            name='schemaattributemodel',
            options={'verbose_name': 'Attribute'},
        ),
        migrations.AlterModelOptions(
            name='schemamodel',
            options={'verbose_name': 'Schema'},
        ),
        migrations.AddField(
            model_name='equipmentmodel',
            name='address',
            field=models.TextField(default='ASRL1::INSTR', verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schemaattributemodel',
            name='data_default',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Default value'),
        ),
        migrations.AlterField(
            model_name='equipmentmodel',
            name='display_name',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Display name'),
        ),
        migrations.AlterField(
            model_name='equipmentmodel',
            name='distinguished_name',
            field=models.CharField(max_length=100, verbose_name='Distinguished name'),
        ),
        migrations.AlterField(
            model_name='schemaattributemodel',
            name='display_name',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Display name'),
        ),
        migrations.AlterField(
            model_name='schemaattributemodel',
            name='distinguished_name',
            field=models.CharField(max_length=100, verbose_name='Distinguished name'),
        ),
        migrations.AlterField(
            model_name='schemamodel',
            name='display_name',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Display name'),
        ),
        migrations.AlterField(
            model_name='schemamodel',
            name='distinguished_name',
            field=models.CharField(max_length=100, verbose_name='Distinguished name'),
        ),
        migrations.AddField(
            model_name='schemaactionmodel',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrumentation.SchemaModel', verbose_name='Schema'),
        ),
        migrations.AddField(
            model_name='constantmodel',
            name='enumeration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrumentation.EnumerationModel', verbose_name='Enumeration'),
        ),
        migrations.AddField(
            model_name='consolecommandmodel',
            name='equipment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='instrumentation.EquipmentModel'),
        ),
        migrations.AddField(
            model_name='schemaattributemodel',
            name='read_operation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='instrumentation.OperationModel', verbose_name='Read operation'),
        ),
        migrations.AddField(
            model_name='schemaattributemodel',
            name='write_operation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writes', to='instrumentation.OperationModel', verbose_name='Write operation'),
        ),
    ]
