# Generated by Django 2.0.5 on 2018-05-19 19:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentation', '0002_auto_20180510_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, default=None, max_length=100000, null=True)),
                ('additional_data', models.TextField(blank=True, default=None, max_length=10000, null=True)),
                ('indicators_data', models.TextField(blank=True, default=None, max_length=10000, null=True)),
                ('markers_data', models.TextField(blank=True, default=None, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EquipmentProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('name', models.CharField(max_length=100)),
                ('data_type', models.CharField(choices=[('date', 'Date'), ('number', 'Number'), ('text', 'Text')], default='text', max_length=100)),
                ('default_value', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrumentation.Equipment', verbose_name='Equipment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_task_id', models.UUIDField(blank=True, default=None, null=True)),
                ('started', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished', models.DateTimeField(blank=True, default=None, null=True)),
                ('configuration_data', models.CharField(blank=True, default=None, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('name', models.CharField(max_length=100)),
                ('data_type', models.CharField(choices=[('date', 'Date'), ('number', 'Number'), ('text', 'Text')], default='text', max_length=100)),
                ('default_value', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrumentation.Process', verbose_name='Process')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('name', models.CharField(max_length=100)),
                ('data_type', models.CharField(choices=[('date', 'Date'), ('number', 'Number'), ('text', 'Text')], default='text', max_length=100)),
                ('value', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='consolecommandmodel',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='constantmodel',
            name='enumeration',
        ),
        migrations.RemoveField(
            model_name='equipmentmodel',
            name='schema',
        ),
        migrations.RemoveField(
            model_name='parametermodel',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='schemaactionmodel',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='schemaactionmodel',
            name='schema',
        ),
        migrations.RemoveField(
            model_name='schemaattributemodel',
            name='read_operation',
        ),
        migrations.RemoveField(
            model_name='schemaattributemodel',
            name='schema',
        ),
        migrations.RemoveField(
            model_name='schemaattributemodel',
            name='write_operation',
        ),
        migrations.DeleteModel(
            name='ConsoleCommandModel',
        ),
        migrations.DeleteModel(
            name='ConstantModel',
        ),
        migrations.DeleteModel(
            name='EnumerationModel',
        ),
        migrations.DeleteModel(
            name='EquipmentModel',
        ),
        migrations.DeleteModel(
            name='OperationModel',
        ),
        migrations.DeleteModel(
            name='ParameterModel',
        ),
        migrations.DeleteModel(
            name='SchemaActionModel',
        ),
        migrations.DeleteModel(
            name='SchemaAttributeModel',
        ),
        migrations.DeleteModel(
            name='SchemaModel',
        ),
        migrations.AddField(
            model_name='execution',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrumentation.Process', verbose_name='Process'),
        ),
        migrations.AddField(
            model_name='dataframe',
            name='execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrumentation.Execution', verbose_name='Execution'),
        ),
    ]
