# Generated by Django 2.0.4 on 2018-04-22 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentation', '0002_auto_20180422_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstantModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distinguished_name', models.CharField(max_length=100, verbose_name='Distinguished name')),
                ('display_name', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Display name')),
                ('description', models.TextField(blank=True, default=None, max_length=5000, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Constant',
            },
        ),
        migrations.CreateModel(
            name='EnumerationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distinguished_name', models.CharField(max_length=100, verbose_name='Distinguished name')),
                ('display_name', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Display name')),
                ('description', models.TextField(blank=True, default=None, max_length=5000, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Enumeration',
            },
        ),
        migrations.AlterModelOptions(
            name='schemaattributemodel',
            options={'verbose_name': 'Attribute'},
        ),
        migrations.AlterModelOptions(
            name='schemamodel',
            options={'verbose_name': 'Schema'},
        ),
        migrations.AddField(
            model_name='constantmodel',
            name='enumeration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrumentation.EnumerationModel', verbose_name='Enumeration'),
        ),
    ]
