# Generated by Django 2.0.5 on 2018-05-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentation', '0003_auto_20180519_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='state',
            field=models.CharField(choices=[('failed', 'Failed'), ('success', 'Success'), ('pending', 'Pending'), ('running', 'Running')], default='pending', max_length=100),
        ),
    ]
