# Generated by Django 2.0.4 on 2018-04-23 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentation', '0003_auto_20180422_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentmodel',
            name='address',
            field=models.TextField(default='GPIB0::14::INSTR', verbose_name='Address'),
            preserve_default=False,
        ),
    ]
