# Generated by Django 2.0.5 on 2018-05-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentation', '0004_execution_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='state',
            field=models.CharField(choices=[('failed', 'Failed'), ('finished', 'Finished'), ('pending', 'Pending'), ('running', 'Running')], default='pending', max_length=100),
        ),
    ]
