# Generated by Django 2.0.5 on 2018-05-19 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentation', '0005_auto_20180519_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='equipments',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='processes', to='instrumentation.Equipment'),
        ),
        migrations.AlterField(
            model_name='equipmentproperty',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_properties', to='instrumentation.Equipment', verbose_name='Equipment'),
        ),
    ]
