# Generated by Django 2.0.5 on 2018-05-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentation', '0006_auto_20180519_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentproperty',
            name='maximum',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='equipmentproperty',
            name='minimum',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='equipmentproperty',
            name='required',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='maximum',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='minimum',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='required',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='process',
            name='equipments',
            field=models.ManyToManyField(related_name='processes', to='instrumentation.Equipment'),
        ),
    ]
