# Generated by Django 2.0.4 on 2018-04-25 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentation', '0006_operationmodel_parametermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaActionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distinguished_name', models.CharField(max_length=100, verbose_name='Distinguished name')),
                ('display_name', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Display name')),
                ('description', models.TextField(blank=True, default=None, max_length=5000, null=True, verbose_name='Description')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrumentation.OperationModel', verbose_name='Operation')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrumentation.SchemaModel', verbose_name='Schema')),
            ],
            options={
                'verbose_name': 'Action',
            },
        ),
        migrations.AddField(
            model_name='schemaattributemodel',
            name='read_operation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='instrumentation.OperationModel', verbose_name='Read operation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schemaattributemodel',
            name='write_operation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='writes', to='instrumentation.OperationModel', verbose_name='Write operation'),
            preserve_default=False,
        ),
    ]
