# Generated by Django 2.0.4 on 2018-04-25 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentation', '0007_auto_20180425_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemaactionmodel',
            name='operation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='instrumentation.OperationModel', verbose_name='Operation'),
        ),
        migrations.AlterField(
            model_name='schemaattributemodel',
            name='read_operation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='instrumentation.OperationModel', verbose_name='Read operation'),
        ),
        migrations.AlterField(
            model_name='schemaattributemodel',
            name='write_operation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writes', to='instrumentation.OperationModel', verbose_name='Write operation'),
        ),
    ]
