# Generated by Django 2.0.4 on 2018-05-10 11:14
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group, User
from django.db import migrations, models


def populate_initial_data(apps, schema_editor):

    user = User.objects.create_superuser("lordoftheflies", email="laszlo.hegedus@cherubits.hu", password="Armageddon0")
    # AttributeError: 'Manager' object has no attribute 'create_user'

    group = Group.objects.create(name="Administrator Group")
    user.groups.add(group)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '__first__')
    ]

    operations = [
        migrations.CreateModel(
            name='FrontendEnpointModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=20)),
                ('relative_uri', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='NoteBookEndpointModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=20)),
                ('local_path', models.FilePathField(max_length=200)),
            ],
        ),

        migrations.RunPython(populate_initial_data)
    ]
